# Generated by Django 5.1.2 on 2024-10-23 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('8ecb0aca-bebb-4569-b7c3-6595bf20a14a'), editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
